### ISSUE TITLE
Can this setup be used in MetaLnx?

### ISSUE THREAD

**Issue by hanytran** [irods-contrib/irods_auth_plugin_openid#28]
Hi,

I would like to ask if this setup can be directly used from metaLnx, or one needs to do another integration (I'm trying to apply keycloak for iRODS and use it in metaLnx).

Thanks, Han

**Comment by trel** [comment]
This unreleased irods_auth_plugin_openid plugin will probably not make it over the finish line - any OpenID or OIDC work will most likely be in concert with the new `pam_interactive` plugin that should land in 4.3.1.

This is the work of the [Authentication Working Group](https://github.com/irods-contrib/irods_working_group_authentication) and will now be tracked in https://github.com/irods/irods/issues/6576.

After that, different clients (including Metalnx) will need to be taught how to use the new `pam_interactive` flow.
